### ISSUE TITLE
Design Header and Footer

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/MedX#3]
## Responsibility:
@aref-asadi 

## Deadline:
18 Aug 2024

## Description:
We need to design a header and footer that aligns with our brand and enhances user experience. The header should provide easy navigation and quick access to essential features, while the footer should offer additional navigation options and include a section for newsletter subscriptions.

## Header Requirements:

- Logo:
The MedX logo should be displayed on the right side of the header.
- Navigation Menu:
A menu with links to key sections of the website, including "Home" and "Contribute," should be available.
- Search Button:
A search button should be included for users to search the site’s content easily.
- User Access:
A section for user login and sign-up should be placed on the left side of the header.

## Footer Requirements:

- Logo and Introduction:
MedX logo should be displayed along with a brief introduction to MedX.
- Quick Access Menu:
A menu providing quick links to sections like "Home," "Contribute," "User Panel," and "Authors" should be included.
- Newsletter Subscription:
Include a section for users to subscribe to the newsletter, complete with CAPTCHA for security.

## Tasks:
- [x]  Design and layout the header according to the specifications. @aref-asadi 
- [x]  Design and layout the footer according to the specifications. @aref-asadi 
- [x]  Review and refine the design. @Sinusealpha

**Comment by aref-asadi** [comment]
V.1:
[Header & Footer design](https://github.com/MedX-Media/MedX/blob/development/design/MedX_website_design-Header_and_Footer.jpg)

**Comment by Sinusealpha** [comment]
thank you dear @aref-asadi for your designs. i'm gonna leave my comments:

1. i think that this text is more suitable for the footer's bio:
«medx یک پلتفرم رسانه‌ای منبع‌باز است که این امکان را به جامعه‌ی علوم‌پزشکی می‌دهد تا در دنیای فناوری سلامت کاوش کنند. یاد بگیرند. به اشتراک بگذارند و حتی مشارکت داشته باشند.»
if you do not agree or want to change my text, that's ok. let's talk about it. it's important. because it's gonna make our first impressions and we should think about each word.

2. the button of "i'm not robot" should be before someone want to subscribe and i'm wondering if the user should click on which button. i think we shouldn't have "i'm not robot" in the first place and if they wanted to subscribe, then they should be faced with that caution. do you agree? but after all, do we totally need robot detectors in this release of our product? i think not.

3. why do we have "حساب کاربری"? what it is covering? just for subscribing? do we really need it? if yes, implementation is easy and can we afford it in the next few days?

there is no more points about this design and that's great. i think it's super-good for a mtp! thank you again.

**Comment by aref-asadi** [comment]
> thank you dear @aref-asadi for your designs. i'm gonna leave my comments:
> 
> 1. i think that this text is more suitable for the footer's bio:
> «medx یک پلتفرم رسانه‌ای منبع‌باز است که این امکان را به جامعه‌ی علوم‌پزشکی می‌دهد تا در دنیای فناوری سلامت کاوش کنند. یاد بگیرند. به اشتراک بگذارند و حتی مشارکت داشته باشند.»
> if you do not agree or want to change my text, that's ok. let's talk about it. it's important. because it's gonna make our first impressions and we should think about each word.
> 
> 2. the button of "i'm not robot" should be before someone want to subscribe and i'm wondering if the user should click on which button. i think we shouldn't have "i'm not robot" in the first place and if they wanted to subscribe, then they should be faced with that caution. do you agree? but after all, do we totally need robot detectors in this release of our product? i think not.
> 
> 3. why do we have "حساب کاربری"? what it is covering? just for subscribing? do we really need it? if yes, implementation is easy and can we afford it in the next few days?
> 
> there is no more points about this design and that's great. i think it's super-good for a mtp! thank you again.

Regarding the introduction text, I took it from the GitHub introduction section because I thought our introduction should be consistent wherever we introduce ourselves. My assumption was that you had considered all scenarios for that introduction, so I didn’t think much about it. However, if you want, we can consider our introduction text as an issue to discuss.

As for your second comment, the "I’m not a robot" button will be implemented via an API, and in my opinion, it doesn’t add much complexity. If a user enters their email and tries to confirm without completing the "I’m not a robot" step, an error message can be displayed, asking them to complete it. I believe having "I’m not a robot" at any stage is necessary, and having it included in our design from the start seems like a good idea. Personally, I get a sense of importance from websites that have the "I’m not a robot" feature.

Also, I didn’t want a pop-up to appear; I wanted all the necessary steps for subscribing to the newsletter to be in one place, making it simple and easy.

Regarding the third comment, clicking on the user account can serve multiple purposes: if the user is not logged in, it will redirect them to the login/registration page, and if they are logged in, it will take them to their account. I should also mention that, from an implementation standpoint, I have considered the simplest approach for now. What was important to me was to have the minimum functionality with the simplest design, and we can gradually work on implementing them. What’s certain is that we need to have a user account, and a button for accessing it will definitely be necessary.

**Comment by Sinusealpha** [comment]
1- engligh and persian languages are different and we obviously will not talk completely the same in those cultures.

2- i'm ok with what you're thinking about capcha. do what you think is correct. i just wondered why users should face with both "subscription" and "i'm not robot" in one session.

3- i think we don't need accounts right now. please provide your reasons.

**Comment by aref-asadi** [comment]
> 1- engligh and persian languages are different and we obviously will not talk completely the same in those cultures.
> 
> 2- i'm ok with what you're thinking about capcha. do what you think is correct. i just wondered why users should face with both "subscription" and "i'm not robot" in one session.
> 
> 3- i think we don't need accounts right now. please provide your reasons.

1. I agree with you, and we can create an issue for further review.

2. Very well.

3. Honestly, I’m considering that when authors are going to be members of the site and have personal pages, there needs to be an account for managing their personal pages and, in the future, their writings. Additionally, in the future, when users can subscribe to the newsletter, become site members, and create personal profiles, there must be a place to manage these. I emphasize that for now, the user accounts will be intended for authors so they can create their profiles.
Could you please explain why we should not have an account page? without considering superhuman.ai.

**Comment by Sinusealpha** [comment]
i'm totally agree with you on 

> in the future, when users can subscribe to the newsletter, become site members, and create personal profiles, there must be a place to manage these.

but isn't it about the future? if not, i'm ok. but isn't it hard to be implemented?

**Comment by aref-asadi** [comment]
> i'm totally agree with you on
> 
> > in the future, when users can subscribe to the newsletter, become site members, and create personal profiles, there must be a place to manage these.
> 
> but isn't it about the future? if not, i'm ok. but isn't it hard to be implemented?

Well, let's talk about this on MTP issue.
